insert into device(devicetype,deviceseries,devicename) values ('3ph','7','NP73E.1-10-1')
insert into device(devicetype,deviceseries,devicename) values ('3ph','7','NP73E.1-11-1')
insert into device(devicetype,deviceseries,devicename) values ('3ph','7','NP73E.3-14-1')
insert into device(devicetype,deviceseries,devicename) values ('1ph','7','NP71E.1-10-1')
insert into device(devicetype,deviceseries,devicename) values ('1ph','7','NP71E.2-1-5')
